version: '3.8'

services:
  activiti6:
    image: activiti6:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./properties/activiti-app.properties:/properties/activiti-app.properties"
      - "./properties/activiti-admin.properties:/properties/activiti-admin.properties"
      - "./properties/db.properties:/properties/db.properties"
      - "./properties/engine.properties:/properties/engine.properties"