version: '3.8'

services:
  activiti6:
    image: activiti6:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
# todo 动态配置文件
#    volumes:
#      - ./activiti-app.properties:/usr/local/tomcat/webapps/activiti-app/WEB-INF/classes/META-INF/activiti-app/activiti-app.properties
#      - ./activiti-admin.properties:/usr/local/tomcat/webapps/activiti-admin/WEB-INF/classes/META-INF/activiti-admin/activiti-admin.properties
#      - ./db.properties:/usr/local/tomcat/webapps/activiti-rest/WEB-INF/classes/db.properties
#      - ./engine.properties:/usr/local/tomcat/webapps/activiti-rest/WEB-INF/classes/engine.properties